/* 燃刻 PWA · 无第三方脚本、无账号、无远程个人数据上传 */
(()=>{'use strict';
const C=window.RankeCore,$=id=>document.getElementById(id),STORE='ranke-mobile-v1';
let state=C.defaults(),storageBlocked=false,corruptRaw=null,conflictBlocked=false,route='today',trainTab=0,scheduleDay=C.dayKey(),foodFilter='all',foodQuery='',optionDraft=null,offlineReady=false,waitingWorker=null,toastTimeout,exportUrl=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Number(x||0).toLocaleString('zh-CN',{maximumFractionDigits:1});
const n2=x=>Number(x||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const btn=(a,l,d={},cls='')=>`<button type="button" data-action="${a}" ${Object.entries(d).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')} class="${cls}">${l}</button>`;
const field=(label,name,value='',type='text',attrs='')=>`<div class="field"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`;
const area=(label,name,value='',attrs='')=>`<div class="field full"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" ${attrs}>${esc(value)}</textarea></div>`;
const select=(label,name,opts,value)=>`<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;
const heading=(title,sub='',right='')=>`<div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div>${right}</div>`;
const empty=(title,sub,action='')=>`<div class="empty"><div class="empty-icon" aria-hidden="true">＋</div><h3>${title}</h3><p>${sub}</p>${action}</div>`;
const currentPlan=()=>state.strength.plans[state.strength.split];
const currentDay=()=>currentPlan().days[trainTab]||currentPlan().days[0];
const todayData=()=>state.daily[C.dateKey()]||(state.daily[C.dateKey()]={checks:[],choices:{},nuts:false});
const mealKey=(m,k,t=state.dietType)=>`${t}_${m}_${k}`;
const currentChoice=(m,k,t=state.dietType)=>{const ops=state.recipes[t][m][k],id=todayData().choices[mealKey(m,k,t)];return ops.find(o=>o.id===id)||ops[0];};
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').hidden=true,3200);}
function save(){state.updatedAt=new Date().toISOString();if(corruptRaw||conflictBlocked){$('saveState').textContent='当前修改未保存';return false;}try{localStorage.setItem(STORE,JSON.stringify(state));storageBlocked=false;$('saveState').textContent='已保存在本机';$('critical').hidden=true;return true;}catch(e){storageBlocked=true;$('saveState').textContent='尚未保存';$('critical').textContent='本机存储不可用或已满。当前修改仅在内存中，请立即到设置导出备份，勿关闭页面。';$('critical').hidden=false;return false;}}
function load(){try{const raw=localStorage.getItem(STORE);if(raw){try{state=C.normalize(C.validateFullState(JSON.parse(raw)));}catch(e){corruptRaw=raw;$('critical').textContent='本机已有数据无法读取，已停止自动覆盖。请到设置下载原始数据，再导入有效备份恢复。';$('critical').hidden=false;}}$('saveState').textContent=corruptRaw?'数据需恢复':'仅保存在本机';}catch(e){storageBlocked=true;$('critical').textContent='无法访问本机存储，请使用非无痕模式。当前可编辑，但请导出备份保存。';$('critical').hidden=false;}}
function dialog(title,body){$('editorBody').innerHTML=`<div class="dialog-head"><h2>${title}</h2>${btn('close','关闭',{},'small ghost')}</div><div class="dialog-body">${body}</div>`;if(!$('editor').open)$('editor').showModal();}
function form(title,kind,body,data={}){dialog(title,`<form data-form="${kind}" ${Object.entries(data).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')}><div class="form-grid">${body}</div><div class="dialog-footer">${btn('close','取消')}<button class="primary" type="submit">保存</button></div></form>`);}
function close(){if($('editor').open)$('editor').close();optionDraft=null;}
function macros(g){return `<div class="grid3">${[['carbs','碳水'],['protein','蛋白质'],['fat','脂肪']].map(([k,l])=>`<div class="metric"><strong>${n(g[k])}<small> g</small></strong><span>${l}目标</span></div>`).join('')}</div>`;}
function splitSums(t=state.dietType){return ['carbs','protein'].map(k=>C.MEALS.reduce((sum,m)=>sum+Number(state.mealSplits[t][m][k]||0),0));}
function splitStatus(t=state.dietType){const [carbs,protein]=splitSums(t),complete=value=>Math.abs(value-100)<.001,label=value=>complete(value)?'已分配完整':value<100?`未分配 ${n(100-value)}%`:`超出 ${n(value-100)}%`;return `<div class="split-summary"><span class="${complete(carbs)?'':'attention'}">碳水合计 ${n(carbs)}% · ${label(carbs)}</span><span class="${complete(protein)?'':'attention'}">蛋白质合计 ${n(protein)}% · ${label(protein)}</span></div>`;}
function updateSplitTotals(){const box=$('splitTotals');if(!box)return;const sums=['carbs','protein'].map(k=>[...document.querySelectorAll(`[data-split-macro="${k}"]`)].reduce((total,input)=>total+Number(input.value||0),0)),complete=value=>Math.abs(value-100)<.001,label=value=>complete(value)?'已分配完整':value<100?`仍有 ${n(100-value)}% 未分配`:`比全天目标多 ${n(value-100)}%`;box.innerHTML=`<span class="${complete(sums[0])?'':'attention'}">碳水合计 <strong>${n(sums[0])}%</strong> · ${label(sums[0])}</span><span class="${complete(sums[1])?'':'attention'}">蛋白质合计 <strong>${n(sums[1])}%</strong> · ${label(sums[1])}</span>`;}
function dateLabel(s){const d=new Date(s);return Number.isFinite(d.getTime())?d.toLocaleDateString('zh-CN',{month:'short',day:'numeric'}):'未知日期';}
function fullDate(s){const d=new Date(s+'T12:00:00');return Number.isFinite(d.getTime())?d.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}):'—';}
function formulaResults(){const details=C.calcDetails(state);if(!details)return '<p class="muted smalltext">尚未填写身体与计划参数。</p>';const p=state.profile;return `<div class="result-grid"><div class="metric"><strong>${n(details.bmi)}</strong><span>BMI · ${details.bmiText}</span></div><div class="metric"><strong>${n(Math.floor(details.bmr))}</strong><span>基础代谢 kcal</span></div><div class="metric"><strong>${n(Math.floor(details.base))}</strong><span>基础日常消耗 kcal</span></div></div><div class="day-result"><div class="row spread"><strong>训练日</strong><span class="tag">平衡 ${n(Math.floor(details.balances.train))} kcal</span></div><div class="calorie-result"><strong>${n(details.goals.train.calories)}</strong><span>kcal 应吃</span></div>${macros(details.goals.train)}<p>包含 ${p.level} kcal 力量训练 + ${p.aerobic} kcal 有氧</p></div><div class="day-result"><div class="row spread"><strong>休息日</strong><span class="tag">平衡 ${n(Math.floor(details.balances.rest))} kcal</span></div><div class="calorie-result"><strong>${n(details.goals.rest.calories)}</strong><span>kcal 应吃</span></div>${macros(details.goals.rest)}<p>包含 ${p.aerobic} kcal 有氧</p></div>${details.fixedCalories>details.goals.train.calories||details.fixedCalories>details.goals.rest.calories?'<div class="notice warning">蛋白质与脂肪的固定热量已超过目标热量，碳水按 0g 计算。请核对参数。</div>':''}`;}
function weightGoalResults(){const goal=C.weightGoal(state);if(!state.profileReady)return '';if(!goal)return '<div class="notice warning">目标体重需低于当前体重，计划周期至少为 1 周。</div>';return `<div class="row spread wrap"><h3>减重目标与时间</h3><span class="tag ${goal.weeklyRate>1?'warn':'accent'}">${goal.pace}</span></div><div class="goal-grid"><div class="metric"><strong>${n(state.profile.targetWeight)}<small> kg</small></strong><span>目标体重</span></div><div class="metric"><strong>${n(goal.loss)}<small> kg</small></strong><span>计划减重</span></div><div class="metric"><strong>${n2(Math.floor((goal.weekly+1e-9)*100)/100)}<small> kg</small></strong><span>每周目标</span></div><div class="metric"><strong>${n2(Math.floor((goal.weeklyRate+1e-9)*100)/100)}<small> %</small></strong><span>每周体重比例</span></div></div><p class="muted smalltext" style="margin-top:12px">${fullDate(goal.start)}（周一）至 ${fullDate(goal.end)}（周日），共 ${state.profile.goalWeeks} 个完整自然周。${goal.weeklyRate>1?'按原网页阈值，此目标被标记为较激进，请核对。':''}</p>`;}
function duration(a){const mins=Math.max(0,Math.floor(((a.endedAt?new Date(a.endedAt).getTime():Date.now())-new Date(a.startedAt).getTime())/60000));return mins>=60?Math.floor(mins/60)+'小时'+mins%60+'分':mins+'分钟';}
function render(){route=location.hash.slice(1).split('?')[0]||'today';if(!['today','training','session','history','diet','foods','schedule','settings'].includes(route))route='today';const fn={today:renderToday,training:renderTraining,session:renderSession,history:renderHistory,diet:renderDiet,foods:renderFoods,schedule:renderSchedule,settings:renderSettings};$('app').innerHTML=fn[route]();document.querySelectorAll('[data-tab]').forEach(a=>a.classList.toggle('active',a.dataset.tab===({session:'training',history:'training',foods:'diet'}[route]||route)));renderTimer();}
function renderToday(){const now=new Date(),assigned=currentPlan().days.find(d=>d.id===currentPlan().week[C.dayKey()]),active=state.strength.active,goals=C.calcGoals(state),rows=state.schedule.days[C.dayKey()],daily=todayData(),done=rows.filter(r=>daily.checks.includes(r.id)).length;return heading('把今天，过成计划',`${now.getMonth()+1}月${now.getDate()}日 · ${C.DAY_NAMES[C.DAYS.indexOf(C.dayKey())]}`,`<span class="tag">我的日常</span>`)+`<div class="dashboard-grid"><section class="card hero wide"><div class="eyebrow">TODAY / STRENGTH</div><div class="row spread"><h2>${active?'继续这次训练':assigned?esc(assigned.name):'今天，由你安排'}</h2><span class="tag">${state.strength.split}分化</span></div><p class="muted">${active?esc(active.parts||'训练已保存，可以随时继续'):assigned?esc(assigned.parts||'还未填写训练部位'):'尚未安排训练日。可以休息，也可以选择一练开始。'}</p><div class="actions">${active?btn('go','继续训练',{route:'session'},'lime'):assigned?btn('start','开始训练',{id:assigned.id},'lime'):btn('go','安排力量训练',{route:'training'},'lime')}${btn('go','查看计划',{route:'training'},'ghost')}</div></section><section class="card"><div class="row spread"><h2>今日作息</h2><span class="tag">${done} / ${rows.length}</span></div>${rows.length?rows.map(r=>timeline(r,true)).join(''):empty('留点秩序给生活','为周一到周日分别安排作息。',btn('go','设置今天',{route:'schedule'},'small'))}<div class="actions">${btn('go','查看一周',{route:'schedule'},'ghost small')}</div></section><section class="card"><div class="row spread"><h2>今天吃什么</h2><span class="tag">${state.dietType==='train'?'训练日':'休息日'}</span></div>${goals?`<p class="muted smalltext">公式计算目标 · ${n(goals[state.dietType].calories)} kcal，不是实际摄入</p>${macros(goals[state.dietType])}`:empty('先填写身体与计划参数','保存后会按原网页公式自动计算。',btn('profile','填写参数',{},'small'))}<div class="divider"></div>${C.MEALS.map(m=>{const labels=['carbs','protein'].map(k=>currentChoice(m,k)).filter(Boolean).flatMap(o=>o.components.map(c=>C.food(state,c.foodId)?.name||'缺失食物'));return `<div class="row spread" style="margin:12px 0;align-items:start"><strong class="nowrap smalltext">${C.MEAL_NAMES[m]}</strong><span class="muted smalltext" style="text-align:right">${esc(labels.join(' + ')||'尚未安排')}</span></div>`;}).join('')}<div class="actions">${btn('go','打开食谱',{route:'diet'},'primary')}</div></section><div class="notice wide"><strong>你的食谱备注</strong><br>${C.NUTS}<label class="inline-check" style="margin-top:10px"><input type="checkbox" data-nuts ${daily.nuts?'checked':''}>今天需要补充时，已完成这 30g 坚果</label><small>这是你指定的提醒；坚果营养未自动计入食谱估算。</small></div></div>`;}
function timeline(r,check){return `<div class="timeline-row"><div class="timeline-time">${esc(r.start||'—')}<small>${r.end&&r.start&&r.end<r.start?'次日 ':''}${esc(r.end)}</small></div><div class="timeline-body"><strong class="${check&&todayData().checks.includes(r.id)?'done-title':''}">${esc(r.title||'未命名事项')}</strong>${r.notes?`<p>${esc(r.notes)}</p>`:''}</div>${check?btn('check-schedule',todayData().checks.includes(r.id)?'✓':'○',{id:r.id},'check-button '+(todayData().checks.includes(r.id)?'done':'')):btn('edit-event','编辑',{id:r.id},'small ghost')}</div>`;}
function renderTraining(){const p=currentPlan(),d=currentDay();return heading('力量训练','先计划，再专注完成每一组。',btn('go','记录',{route:'history'},'small'))+`<div class="segment">${[4,5].map(n=>btn('split',n===4?'四分化':'五分化',{n},state.strength.split===n?'active':'')).join('')}</div>${state.strength.active?`<div class="notice row spread"><span>有一次未结束的训练</span>${btn('go','继续',{route:'session'},'small primary')}</div>`:''}<div class="scroll-tabs">${p.days.map((d,i)=>btn('train-tab',esc(d.name),{i},trainTab===i?'active':'')).join('')}</div><section class="card hero"><div class="eyebrow">SESSION ${trainTab+1} / ${state.strength.split}</div><div class="row spread"><h2>${esc(d.name)}</h2>${btn('edit-day','编辑',{},'small ghost')}</div><p class="muted">${esc(d.parts||'点击编辑，填写训练部位')}</p>${d.notes?`<p class="smalltext prewrap">${esc(d.notes)}</p>`:''}<div class="row wrap"><span class="tag">${d.exercises.length} 个动作</span><span class="tag">${d.exercises.reduce((a,e)=>a+e.sets,0)} 组</span></div><div class="actions">${btn('start','开始这一练',{id:d.id},'lime')}</div></section><div class="section-title"><h2>动作顺序</h2>${btn('edit-exercise','＋ 添加动作',{},'small')}</div>${d.exercises.length?d.exercises.map((e,i)=>`<article class="card"><div class="exercise-head"><span class="exercise-index">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(e.name||'未命名动作')}</h3><p>${e.sets} 组 × ${esc(e.reps||'待填')} 次 · ${e.unit==='自重'?'自重':esc(e.weight||'待填')+' '+e.unit}</p></div>${btn('edit-exercise','编辑',{id:e.id},'small ghost')}</div><div class="row wrap"><span class="tag">组间休息 ${e.rest} 秒</span>${btn('move-exercise','上移',{id:e.id,dir:-1},'small ghost')}${btn('move-exercise','下移',{id:e.id,dir:1},'small ghost')}</div>${e.notes?`<p class="exercise-notes">${esc(e.notes)}</p>`:''}</article>`).join(''):`<section class="card">${empty('写下你的第一组动作','自行填写动作、组数、次数、重量和备注。不会预设训练强度。',btn('edit-exercise','添加动作',{},'primary'))}</section>`}<section class="card"><div class="row spread"><h2>每周安排</h2>${btn('edit-week','安排',{},'small')}</div><p class="muted smalltext">四分化与五分化独立保存；同一练可以安排多次，留空表示休息或待定。</p><div class="day-tabs">${C.DAYS.map((key,i)=>`<div style="text-align:center"><span class="smalltext">${C.DAY_NAMES[i]}</span><small class="muted" style="display:block;margin-top:8px;overflow-wrap:anywhere">${esc(p.days.find(d=>d.id===p.week[key])?.name||'—')}</small></div>`).join('')}</div></section><p class="muted smalltext">此处用于记录你自行制定的计划，不自动推荐动作或训练负荷。若感到疼痛或不适，请停止训练。</p>`;}
function renderSession(){const a=state.strength.active;if(!a)return heading('训练中')+`<section class="card">${empty('现在没有进行中的训练','从计划里选择一练开始。',btn('go','打开计划',{route:'training'},'primary'))}</section>`;const stats=C.sessionStats(a);return heading(esc(a.name),esc(a.parts||'专注当下，每组都会保存。'),btn('go','收起',{route:'training'},'small'))+`<section class="card"><div class="row spread"><div><div class="eyebrow">TRAINING IN PROGRESS</div><strong id="sessionProgress">${stats.done} / ${stats.total} 组已完成</strong></div><span class="tag">${a.split}分化</span></div><div class="progress"><div id="sessionProgressBar" style="width:${stats.total?stats.done/stats.total*100:0}%"></div></div><p class="muted smalltext" style="margin:0">预填的是计划值。请按实际填写次数与重量，再勾选完成；次数范围可记录，但不会计入训练量。</p>${a.planNotes?`<p class="exercise-notes">${esc(a.planNotes)}</p>`:''}</section>${a.exercises.map((e,i)=>`<section class="card"><div class="exercise-head"><span class="exercise-index">${i+1}</span><div><h3>${esc(e.name)}</h3><p>${e.sets} 组 × ${esc(e.reps||'—')} 次 · ${e.unit==='自重'?'自重':esc(e.weight||'—')+' '+e.unit}</p></div>${btn('rest','休息',{seconds:e.rest,label:e.name},'small')}</div>${e.notes?`<p class="exercise-notes">${esc(e.notes)}</p>`:''}<div class="set-grid labels"><span>组</span><span>实际次数</span><span>${e.unit==='自重'?'附加重量（不计量）':'实际重量 / '+e.unit}</span><span>完成</span></div>${e.setsLog.map((s,j)=>`<div class="set-grid ${s.done?'completed':''}"><span class="set-no">${j+1}</span><input type="text" inputmode="numeric" maxlength="30" data-log="reps" data-e="${i}" data-s="${j}" value="${esc(s.reps)}" aria-label="${esc(e.name)}第${j+1}组实际次数"><input type="text" inputmode="decimal" maxlength="20" data-log="weight" data-e="${i}" data-s="${j}" value="${esc(s.weight)}" aria-label="${esc(e.name)}第${j+1}组实际重量">${btn('set-done',s.done?'✓':'○',{e:i,s:j},'check-button '+(s.done?'done':''))}</div>`).join('')}</section>`).join('')}<section class="card"><div class="field"><label for="sessionNotes">本次训练备注</label><textarea id="sessionNotes" maxlength="3000" placeholder="状态、动作感受、下次需要调整的地方…">${esc(a.notes)}</textarea></div><div class="actions">${btn('finish-session','结束并保存记录',{},'primary')}</div><div class="actions">${btn('discard-session','放弃本次训练',{},'danger ghost small')}</div></section><p class="muted smalltext">训练快照独立于计划；中途编辑计划不会改动这次记录。组间计时不保证锁屏或后台响铃。</p>`;}
function renderHistory(){const hist=state.strength.history.slice().reverse();return heading('训练记录','每次努力，都留有记录。',btn('go','返回',{route:'training'},'small'))+`<div class="grid3" style="margin-bottom:18px"><div class="metric"><strong>${hist.length}</strong><span>累计训练</span></div><div class="metric"><strong>${hist.reduce((n,a)=>n+C.sessionStats(a).done,0)}</strong><span>完成组数</span></div><div class="metric"><strong>${hist.filter(a=>Date.now()-new Date(a.endedAt).getTime()<7*86400000).length}</strong><span>近 7 天训练</span></div></div><section class="card">${hist.length?hist.map(a=>{const s=C.sessionStats(a);return `<div class="history-row"><div><h3>${esc(a.name)}</h3><p>${dateLabel(a.startedAt)} · ${s.done}/${s.total} 组 · ${duration(a)}</p><span class="muted smalltext">${esc(a.parts)}</span></div>${btn('history-detail','查看',{id:a.id},'small')}</div>`;}).join(''):empty('还没有训练记录','完成一练后，实际次数、重量和备注会出现在这里。')}</section>`;}
function renderDiet(){const t=state.dietType,g=C.calcGoals(state);return heading('我的食谱','按目标配餐，参考食物可以直接选用。',btn('go','食品库',{route:'foods'},'small'))+`<div class="segment">${btn('diet-type','训练日',{t:'train'},t==='train'?'active':'')}${btn('diet-type','休息日',{t:'rest'},t==='rest'?'active':'')}</div><section class="card"><div class="row spread"><h2>全天目标</h2>${g?`<span class="tag">${n(g[t].calories)} kcal</span>`:''}</div>${g?macros(g[t]):'<div class="notice warning">尚未填写身体与计划参数，暂不计算食物重量。</div>'}${splitStatus(t)}<div class="actions">${btn('edit-splits','四餐分配',{},'small ghost')}${btn('profile',g?'修改参数':'填写参数',{},'small ghost')}</div></section><div class="notice">${C.NUTS}<br><small>坚果及烹调油、蔬菜等未自动计入下方估算；这不是完整实际摄入记录。</small></div><div class="recipe-grid">${C.MEALS.map(m=>mealCard(m)).join('')}</div><section class="card" style="margin-top:18px"><h3>怎样读这份食谱</h3><p class="muted smalltext">每餐分别从碳水组、蛋白质组中各选一个方案；同一方案里的食物一起吃，不同方案互为替换。“选作今天”只决定今日展示，不代表已经进食。</p><p class="muted smalltext">各餐比例直接乘以全天目标计算，合计可以不足或超过 100%。参考资料大多只提供一种营养素，未提供不代表为零；重量向下取整，存在取整误差。</p><div class="actions">${btn('export-image','生成宽版食谱图',{kind:'diet'},'small')}${btn('copy-diet','复制到'+(t==='train'?'休息日':'训练日'),{},'small ghost')}</div></section>`;}
function mealCard(m){const t=state.dietType,target=C.mealTarget(state,t,m);return `<section class="card"><div class="row spread"><h2>${C.MEAL_NAMES[m]}</h2><span class="tag">${target?'碳 '+target.carbs+'g · 蛋 '+target.protein+'g':'未设目标'}</span></div>${['carbs','protein'].map(k=>{const ops=state.recipes[t][m][k],chosen=currentChoice(m,k);return `<div class="macro-heading">${k==='carbs'?'碳水组合':'蛋白质组合'} · ${ops.length>1?'备选方案只选一个':'可加入一种或多种食物'}</div>${ops.map((o,i)=>{const r=C.optionResult(state,o,k,target?.[k]||0);return `<div class="option ${chosen?.id===o.id?'selected':''}"><div class="option-header"><span>${esc(o.name||'方案 '+(i+1))}${chosen?.id===o.id?' · 今日选用':''}</span>${btn('edit-option','编辑',{meal:m,macro:k,id:o.id},'small ghost')}</div>${r.items.map(x=>`<div class="food-quantity"><span>${esc(x.name)}${x.estimated?' <span class="tag">估算</span>':''}</span><strong>${target&&!x.missing?n(x.quantity)+x.unit:'—'}</strong></div>`).join('')}${r.fixedExceeded?'<p class="split-alert">固定份数已超过本组目标，请核对。</p>':''}${r.items.some(x=>x.missing||x.invalid)?'<p class="split-alert">有食物缺失或不含目标营养素，请编辑修复。</p>':''}${target?`<p class="muted smalltext" style="margin:8px 0 0">已知部分 · 碳 ${n(r.totals.carbs)}g / 蛋 ${n(r.totals.protein)}g / 脂 ${n(r.totals.fat)}g</p>`:''}${ops.length>1&&chosen?.id!==o.id?`<div class="actions">${btn('choose-option','选作今天',{meal:m,macro:k,id:o.id},'small')}</div>`:''}</div>`;}).join('')}<div class="actions">${btn('edit-option','＋ '+(ops.length?'新增备选':'添加组合'),{meal:m,macro:k},'small ghost')}</div>`;}).join('')}</section>`;}
function renderFoods(){return heading('食品库','内置 97 项资料，可直接加入食谱。',btn('go','返回',{route:'diet'},'small'))+`<div class="notice warning smalltext">原资料说明未经独立核验。生熟状态、GI 与营养比例均为参考，请优先核对实际包装。缺少的营养素不按“真实为零”理解。</div><div class="search-area"><input type="search" id="foodSearch" value="${esc(foodQuery)}" placeholder="搜索食物、类别或说明" aria-label="搜索食品库"><div class="segment">${[['all','全部'],['carbs','碳水'],['protein','蛋白质'],['custom','自定义']].map(([k,l])=>btn('food-filter',l,{k},foodFilter===k?'active':'')).join('')}</div></div><div class="row spread" style="margin:10px 0"><span id="foodCount" class="muted smalltext"></span>${btn('edit-food','＋ 自定义食物',{},'small')}</div><section class="card food-list" id="foodResults">${foodResults()}</section>`;}
function foodResults(){const list=C.foods(state).filter(f=>(foodFilter==='all'||foodFilter==='custom'&&!f.referenceEstimate||foodFilter==='carbs'&&C.eligible(f,'carbs')||foodFilter==='protein'&&C.eligible(f,'protein'))&&[f.name,f.referenceNote,f.referenceGroup,f.note].join(' ').toLowerCase().includes(foodQuery.toLowerCase()));setTimeout(()=>{if($('foodCount'))$('foodCount').textContent=`${list.length} 项 · 参考资料＋自定义`;},0);return list.length?list.map(f=>`<article class="food-card"><div class="row"><div><h3>${esc(f.name)}</h3><div class="row wrap"><span class="tag">${esc(f.referenceGroup||'自定义')}</span>${f.referenceGi?`<span class="tag">${f.referenceGi} GI · 原资料</span>`:''}${f.referenceValue?`<span class="smalltext">${f.referenceMacro==='carbs'?'碳水':'蛋白质'} ${esc(f.referenceValue)}</span>`:''}</div></div>${btn('food-use','配餐',{id:f.id},'small primary')}</div>${!f.referenceEstimate?`<p>每${f.measure==='perItem'?'1'+esc(f.referenceUnit):'100g'} · 碳 ${n(f.carbs)}g / 蛋 ${n(f.protein)}g / 脂 ${n(f.fat)}g · ${n(f.kcal)} kcal</p>`:''}<details><summary>查看说明${f.referenceEstimate?'（原资料）':''}</summary><p>${esc(f.referenceNote||f.note||'暂无额外说明')}</p>${!f.referenceEstimate?btn('edit-food','编辑食物',{id:f.id},'small'):btn('clone-food','复制为自定义，补全营养',{id:f.id},'small')}</details></article>`).join(''):empty('没有找到食物','试试缩短关键词，或创建自定义食物。');}
function renderSchedule(){const rows=state.schedule.days[scheduleDay];return heading('一周作息','七天各自安排，不受工作日模板限制。',btn('export-image','导出图',{kind:'schedule'},'small'))+`<div class="day-tabs">${C.DAYS.map((d,i)=>btn('schedule-day',C.DAY_NAMES[i]+`<small>${state.schedule.days[d].length}项</small>`,{day:d},scheduleDay===d?'active':'')).join('')}</div><section class="card"><div class="row spread"><h2>${C.DAY_NAMES[C.DAYS.indexOf(scheduleDay)]}</h2>${btn('edit-event','＋ 添加',{},'small primary')}</div>${rows.length?rows.map(r=>timeline(r,false)).join(''):empty('这一天，留给你安排','可填写任意时段，跨夜时间会标注次日。')}<div class="actions">${btn('copy-schedule','复制这天到…',{},'small ghost')}${btn('schedule-example','填入示例',{},'small ghost')}</div></section><section class="card"><div class="row spread"><h2>一周备注</h2>${btn('schedule-notes','编辑',{},'small')}</div><p class="notes-text">${esc(state.schedule.notes||'例如：周末起床可晚一点；训练时间按实际调整。')}</p></section>`;}
function renderSettings(){const standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone;return heading('设置与数据','你的计划，保存在这台设备。')+`<section class="card"><div class="row spread"><div><h2 style="margin-bottom:2px">身体参数与计算结果</h2><p class="muted smalltext">沿用原网页公式自动计算</p></div>${btn('profile',state.profileReady?'编辑参数':'填写参数',{},'small')}</div>${formulaResults()}<div class="divider"></div>${weightGoalResults()}</section><section class="card"><h2>备份与迁移</h2><p class="muted smalltext">没有云端同步。删除网站数据、更换网址、移除主屏幕应用或换手机，都可能丢失本机记录。请定期导出备份，保存在“文件”或 iCloud 云盘。</p><div class="actions">${btn('backup','导出全部数据',{},'primary')}${btn('import','导入 JSON 备份')}</div>${corruptRaw?`<div class="actions">${btn('raw-backup','下载无法读取的原始数据',{},'danger')}</div>`:''}<p class="muted smalltext" style="margin:12px 0 0">支持本应用备份，以及原「健身系统」导出的完整 JSON。导入前会显示摘要，并要求确认替换。</p></section><section class="card"><div class="row spread"><h2>iPhone 使用</h2><span class="tag">${standalone?'已在独立模式':'当前为网页模式'}</span></div><ol class="muted smalltext" style="padding-left:20px"><li>将文件包上传到 Cloudflare Pages，打开 HTTPS 网址。</li><li>在 iPhone 的 Safari 中打开，点“分享”→“添加到主屏幕”。</li><li>从主屏幕打开燃刻，等待离线资源准备好；再导入个人备份。</li></ol><p class="smalltext muted">离线状态：<strong id="offlineStatus">${offlineReady?'已缓存核心文件':location.protocol==='file:'?'本地文件预览，不支持离线安装':'正在确认；首次打开请保持联网'}</strong></p><p class="smalltext muted">清除 Safari 的网站数据可能移除本机记录；操作前请导出备份。离线可编辑计划和训练记录，不支持跨设备同步。</p>${btn('check-update','检查应用更新',{},'small')}</section><section class="card"><h2>隐私与版本</h2><p class="muted smalltext">燃刻 1.1.0 · 无广告、无统计脚本、无第三方资源。个人表单与备份不发送给服务器；托管平台仍可能记录正常页面访问日志。</p><p class="muted smalltext">本工具不是医疗或营养建议。参考食物并非完整营养标签，训练动作和负荷由你自行决定。</p><div class="actions">${btn('reset','清空本机数据',{},'danger small ghost')}</div></section>`;}

function editProfile(){const p=state.profile;form('身体与计划参数','profile',`<div class="notice field full">保存后按原网页公式自动计算训练日、休息日的平衡热量、目标热量及三大营养素，不再区分计算模式。</div>${select('性别参数','gender',[['male','男'],['female','女']],p.gender)}${field('当前体重 / kg','weight',p.weight,'number','required min="30" max="400" step="0.1" inputmode="decimal"')}${field('身高 / cm','height',p.height,'number','required min="100" max="250" step="0.1" inputmode="decimal"')}${field('年龄','age',p.age,'number','required min="14" max="100" step="1"')}${select('力量训练热量 / kcal','level',[[150,'150'],[200,'200'],[250,'250']],p.level)}${field('有氧热量 / kcal','aerobic',p.aerobic,'number','min="0" max="3000" step="1" required')}${field('蛋白质系数 / g·kg⁻¹','protein',p.protein,'number','min="0" max="4" step="0.1" required')}${field('目标体重 / kg','targetWeight',p.targetWeight,'number','required min="30" max="400" step="0.1"')}${field('目标起始日期','goalStartDate',p.goalStartDate,'date','required')}${field('目标周期 / 周','goalWeeks',p.goalWeeks,'number','required min="1" max="260" step="1"')}<div class="field full"><small>目标热量沿用原网页的“平衡热量 × 64%”；脂肪按体重阈值计算，蛋白质按体重与系数计算，余下热量分配给碳水。</small></div>`);}
function editExercise(eid){const e=currentDay().exercises.find(x=>x.id===eid)||{name:'',sets:3,reps:'',weight:'',unit:'kg',rest:90,notes:''};form(eid?'编辑动作':'添加动作','exercise',`${field('动作名称','name',e.name,'text','required maxlength="80" placeholder="例如：杠铃卧推"')}${field('组数','sets',e.sets,'number','required min="1" max="30" step="1"')}${field('每组次数','reps',e.reps,'text','maxlength="30" placeholder="例如：8–12"')}${field('重量','weight',e.weight,'text','inputmode="decimal" maxlength="20" placeholder="例如：40"')}${select('重量单位','unit',[['kg','kg'],['lb','lb'],['自重','自重']],e.unit)}${field('组间休息 / 秒','rest',e.rest,'number','required min="0" max="3600" step="1"')}${area('动作备注','notes',e.notes,'maxlength="2000" placeholder="动作要点、热身组、器械设置等"')}${eid?`<div class="field full">${btn('delete-exercise','删除这个动作',{id:eid},'danger')}</div>`:''}`,{id:eid||''});}
function editFood(fid,clone=false){const original=C.food(state,fid),f=original?C.copy(original):{name:'',measure:'per100g',carbs:0,protein:0,fat:0,kcal:0,referenceUnit:'份',note:''};if(clone){f.name+='（自定义）';f.note='源自参考资料；请核对并补全营养标签。\n'+(f.referenceNote||'');}form(clone?'补全参考食物':fid?'编辑食物':'自定义食物','food',`<div class="notice field full">请填写同一计量单位的完整营养。按“每份”录入时，可将一份定义成一个、一盒或一袋；食谱将取整数份。</div>${field('食物名称','name',f.name,'text','required maxlength="60"')}${select('计量基准','measure',[['per100g','每 100g'],['perItem','每 1 份']],f.measure)}${field('份的显示单位','referenceUnit',f.referenceUnit||'份','text','maxlength="12" placeholder="个 / 盒 / 袋"')}${select('食物分类','category',[['staple','主食'],['protein','肉蛋'],['dairy','乳制品'],['fruitveg','蔬果'],['fat','脂肪来源'],['mixed','混合食物']],f.category||'mixed')}${['carbs','protein','fat','kcal'].map((k,i)=>field(['碳水 / g','蛋白质 / g','脂肪 / g','热量 / kcal（0 则自动计算）'][i],k,f[k],'number','required min="0" max="50000" step="0.1"')).join('')}${area('备注','note',f.note||'','maxlength="1500"')}${fid&&!clone?`<div class="field full">${btn('delete-food','删除自定义食物',{id:fid},'danger')}</div>`:''}`,{id:clone?'':fid||''});}
function optionEditor(m,k,oid,foodId){const existing=state.recipes[state.dietType][m][k].find(o=>o.id===oid);optionDraft={meal:m,macro:k,type:state.dietType,option:existing?C.copy(existing):{id:C.uid(),name:'',components:[]},isNew:!existing};if(foodId)optionDraft.option.components.push({id:C.uid(),foodId,share:100,fixedCount:0});renderOptionEditor();}
function syncOptionDraft(){if(!optionDraft)return;const form=document.querySelector('[data-form="option"]');if(!form)return;optionDraft.option.name=form.elements.name.value;form.querySelectorAll('[data-component]').forEach(el=>{const c=optionDraft.option.components.find(c=>c.id===el.dataset.component);if(c){c.share=C.num(el.querySelector('[name="share"]').value,0,100,100);c.fixedCount=C.num(el.querySelector('[name="fixedCount"]')?.value||0,0,1000);}});}
function renderOptionEditor(){const d=optionDraft,o=d.option;dialog(`${C.MEAL_NAMES[d.meal]} · ${d.macro==='carbs'?'碳水':'蛋白质'}组合`,`<form data-form="option"><div class="form-grid">${field('方案名称（可选）','name',o.name,'text','maxlength="80" placeholder="例如：米饭＋红薯"')}</div><p class="muted smalltext" style="margin-top:14px">此方案中的食物一起吃。自动分配按“份额”比例分摊本组目标，不要求合计为 100。按份计量的食物可固定数量，0 表示自动。</p>${o.components.map(c=>{const f=C.food(state,c.foodId);return `<div class="component" data-component="${c.id}"><div class="row spread"><h3>${esc(f?.name||'食物已缺失')}</h3>${btn('remove-component','移除',{id:c.id},'small ghost')}</div><div class="form-grid"><div class="field"><label for="share-${c.id}">自动分配份额</label><input id="share-${c.id}" name="share" value="${c.share}" type="number" required min="0" max="100" step="0.1"></div>${f?.measure==='perItem'?`<div class="field"><label for="fixed-${c.id}">固定数量 / ${esc(f.referenceUnit||'份')}</label><input id="fixed-${c.id}" name="fixedCount" value="${c.fixedCount}" type="number" required min="0" max="1000" step="1"></div>`:''}</div></div>`;}).join('')}<div class="actions">${btn('pick-food','＋ 从食品库加入食物',{},'primary')}</div><div class="dialog-footer">${btn('close','取消')}<button type="submit" class="primary">保存组合</button></div>${!d.isNew?`<div class="actions">${btn('delete-option','删除此备选方案',{},'danger small ghost')}</div>`:''}</form>`);}
function picker(){syncOptionDraft();dialog('选择食物',`<input type="search" id="pickerSearch" placeholder="搜索参考资料与自定义食物" aria-label="搜索可用食物"><p class="muted smalltext" style="margin:10px 0">只显示可用于${optionDraft.macro==='carbs'?'碳水':'蛋白质'}组的食物。</p><div id="pickerResults">${pickerRows('')}</div><div class="actions">${btn('back-option','返回组合',{},'ghost')}</div>`);}
function pickerRows(q){return C.foods(state).filter(f=>C.eligible(f,optionDraft.macro)&&f.name.toLowerCase().includes(q.toLowerCase())).map(f=>`<div class="food-card row spread"><div><strong>${esc(f.name)}</strong><p>${f.referenceEstimate?'参考估算 · '+esc(f.referenceValue):'每'+(f.measure==='perItem'?'1'+esc(f.referenceUnit):'100g')+' · '+n(f[optionDraft.macro])+'g'}</p></div>${btn('add-component','加入',{id:f.id},'small')}</div>`).join('')||empty('没有找到','可到食品库添加自定义食物。');}
function foodUse(fid){const f=C.food(state,fid),opts=['carbs','protein'].filter(k=>C.eligible(f,k));if(!opts.length)return toast('此食物不含可配餐的碳水或蛋白质，可记录在备注里。');form('用这项食物建立食谱','food-use',`<div class="field full"><h3>${esc(f.name)}</h3><p class="muted smalltext">将建立一个新的备选方案；保存后可编辑它，加入其他食物组成组合。</p></div>${select('日型','type',[['train','训练日'],['rest','休息日']],state.dietType)}${select('哪一餐','meal',C.MEALS.map(m=>[m,C.MEAL_NAMES[m]]),'breakfast')}${select('营养组','macro',opts.map(k=>[k,k==='carbs'?'碳水':'蛋白质']),opts[0])}`,{id:fid});}
function editEvent(eid){const r=state.schedule.days[scheduleDay].find(r=>r.id===eid)||{start:'',end:'',title:'',notes:''};form('编辑'+C.DAY_NAMES[C.DAYS.indexOf(scheduleDay)]+'作息','event',`${field('开始时间','start',r.start,'time','required')}${field('结束时间','end',r.end,'time','required')}${field('事项','title',r.title,'text','required maxlength="150"')}${area('备注','notes',r.notes,'maxlength="1000"')}${eid?`<div class="field full">${btn('delete-event','删除此事项',{id:eid},'danger')}</div>`:''}`,{id:eid||''});}
function renderTimer(){const el=$('timerBar'),t=state.timer;el.hidden=!t;document.body.classList.toggle('has-timer',!!t);if(!t)return;const remain=Math.max(0,Math.ceil((t.endAt-Date.now())/1000));el.classList.toggle('ready',remain===0);el.innerHTML=`<div><small>${esc(t.label||'组间休息')}</small><strong>${remain?String(Math.floor(remain/60)).padStart(2,'0')+':'+String(remain%60).padStart(2,'0'):'休息结束'}</strong></div><div class="row">${btn('timer-add','＋30秒')}${btn('timer-stop',remain?'结束':'收起')}</div>`;}
function startRest(sec,label){if(!Number(sec))return toast('这个动作没有设置休息时间');state.timer={endAt:Date.now()+Number(sec)*1000,label};save();renderTimer();}
function historyDetail(id){const a=state.strength.history.find(x=>x.id===id);if(!a)return;const st=C.sessionStats(a);dialog(esc(a.name),`<p class="muted smalltext">${dateLabel(a.startedAt)} · ${duration(a)} · 完成 ${st.done}/${st.total} 组</p><p class="muted smalltext">记录训练量 ${n(st.volumeKg)} kg·次${st.volumeLb?' / '+n(st.volumeLb)+' lb·次':''}；仅统计已勾选且实际次数为单一数字的负重组，不包含自重。</p>${a.exercises.map(e=>`<h3>${esc(e.name)}</h3><div class="table-scroll"><table><thead><tr><th>组</th><th>次数</th><th>${e.unit}</th><th>状态</th></tr></thead><tbody>${e.setsLog.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.reps||'—')}</td><td>${esc(s.weight||'—')}</td><td>${s.done?'完成':'未完成'}</td></tr>`).join('')}</tbody></table></div>${e.notes?`<p class="notes-text">${esc(e.notes)}</p>`:''}`).join('')}<h3 style="margin-top:18px">训练备注</h3><p class="prewrap muted">${esc(a.notes||'无')}</p><div class="actions">${btn('delete-history','删除这条记录',{id:a.id},'danger small')}${btn('close','关闭',{},'primary')}</div>`);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportBackup(){download(new Blob([JSON.stringify(C.backup(state),null,2)],{type:'application/json'}),`燃刻_备份_${C.dateKey()}.json`);toast('已发起下载，请确认文件已保存');}
function summary(s){return `${s.foods.length} 项自定义食物、${C.DAYS.reduce((n,d)=>n+s.schedule.days[d].length,0)} 条作息、${Object.values(s.recipes).flatMap(t=>Object.values(t)).reduce((n,m)=>n+m.carbs.length+m.protein.length,0)} 个配餐方案、${s.strength.history.length} 条训练记录${s.strength.active?'，以及 1 次进行中的训练':''}`;}
async function importFile(file){if(!file)return;if(file.size>10*1024*1024)return toast('备份超过 10MB，未导入');try{const result=C.importBackup(JSON.parse(await file.text()));dialog('确认导入备份',`<p>${esc(summary(result.state))}</p><div class="notice warning">这会替换当前设备的全部应用数据。请先导出当前备份。${result.legacy?'旧版营养目标将沿用原公式，请在设置中核对；没有包含力量训练记录。':''}</div><p class="muted smalltext">配餐食物编号会保留。找不到的自定义食物将显示缺失提醒，不会悄悄替换成别的食物。</p><div class="actions">${btn('backup','先备份当前数据')}${btn('confirm-import','确认替换',{},'primary')}</div>`);pendingImport=result.state;}catch(e){toast('导入失败：'+e.message);}finally{$('importFile').value='';}}
let pendingImport=null;
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b)return;const d=b.dataset,a=d.action;try{switch(a){
case 'go':if(route==='today'&&d.route==='schedule')scheduleDay=C.dayKey();close();location.hash=d.route;break;
case 'close':close();break;
case 'profile':editProfile();break;
case 'split':state.strength.split=Number(d.n);trainTab=0;save();render();break;
case 'train-tab':trainTab=Number(d.i);render();break;
case 'edit-day':{const x=currentDay();form('训练日信息','day',`${field('训练日名称','name',x.name,'text','required maxlength="80"')}${field('训练部位','parts',x.parts,'text','maxlength="150" placeholder="例如：胸部 / 肱三头肌"')}${area('训练日备注','notes',x.notes,'maxlength="3000"')}`);break;}
case 'edit-exercise':editExercise(d.id);break;
case 'delete-exercise':if(confirm('删除这个计划动作？已有训练记录不受影响。')){currentDay().exercises=currentDay().exercises.filter(e=>e.id!==d.id);save();close();render();}break;
case 'move-exercise':{const es=currentDay().exercises,i=es.findIndex(e=>e.id===d.id),j=i+Number(d.dir);if(j>=0&&j<es.length){[es[i],es[j]]=[es[j],es[i]];save();render();}break;}
case 'edit-week':{const p=currentPlan();form('安排一周训练','week',C.DAYS.map((d,i)=>select(C.DAY_NAMES[i],d,[['','休息 / 待定'],...p.days.map(x=>[x.id,x.name+(x.parts?' · '+x.parts:'')])],p.week[d])).join(''));break;}
case 'start':if(state.strength.active){location.hash='session';toast('先继续或结束当前训练');break;}state.strength.active=C.startSession(currentPlan().days.find(x=>x.id===d.id),state.strength.split);save();location.hash='session';break;
case 'set-done':{const e=state.strength.active.exercises[Number(d.e)],s=e.setsLog[Number(d.s)];s.done=!s.done;if(s.done&&e.rest)startRest(e.rest,e.name);save();render();break;}
case 'rest':startRest(d.seconds,d.label);break;
case 'timer-add':if(state.timer){state.timer.endAt=Math.max(Date.now(),state.timer.endAt)+30000;save();renderTimer();}break;
case 'timer-stop':state.timer=null;save();renderTimer();break;
case 'finish-session':{const a=state.strength.active,st=C.sessionStats(a);if(!confirm(st.done<st.total?`仅完成 ${st.done}/${st.total} 组，仍要结束并保存记录吗？`:'结束并保存这次训练吗？'))break;a.endedAt=new Date().toISOString();state.strength.history.push(a);state.strength.active=null;state.timer=null;save();location.hash='history';toast('训练记录已保存');break;}
case 'discard-session':if(confirm('放弃这次训练？本次实际记录将删除，计划保留。')){state.strength.active=null;state.timer=null;save();location.hash='training';}break;
case 'history-detail':historyDetail(d.id);break;
case 'delete-history':if(confirm('永久删除这条训练记录？可从你此前导出的备份恢复。')){state.strength.history=state.strength.history.filter(x=>x.id!==d.id);save();close();render();}break;
case 'diet-type':state.dietType=d.t;save();render();break;
case 'edit-splits':{const t=state.dietType;form('四餐分配 · '+(t==='train'?'训练日':'休息日'),'splits',`<div class="notice field full">各餐按“全天目标 × 本餐比例”直接计算。两列合计可以不足或超过 100%，不会自动归一化；脂肪按碳水与蛋白质比例的平均值分配。</div><div id="splitTotals" class="split-summary live field full"></div>`+C.MEALS.map(m=>`<div class="field full meal-divider"><strong>${C.MEAL_NAMES[m]}</strong></div>${field('碳水占比 / %',m+'_carbs',state.mealSplits[t][m].carbs,'number','required min="0" max="100" step="0.1" inputmode="decimal" data-split-macro="carbs"')}${field('蛋白质占比 / %',m+'_protein',state.mealSplits[t][m].protein,'number','required min="0" max="100" step="0.1" inputmode="decimal" data-split-macro="protein"')}`).join(''));setTimeout(updateSplitTotals,0);break;}
case 'edit-option':optionEditor(d.meal,d.macro,d.id);break;
case 'pick-food':picker();break;
case 'back-option':renderOptionEditor();break;
case 'add-component':if(optionDraft.option.components.length>=50)return toast('每个组合最多 50 项食物');optionDraft.option.components.push({id:C.uid(),foodId:d.id,share:100,fixedCount:0});renderOptionEditor();break;
case 'remove-component':syncOptionDraft();optionDraft.option.components=optionDraft.option.components.filter(c=>c.id!==d.id);renderOptionEditor();break;
case 'delete-option':if(confirm('删除此备选方案？')){const x=optionDraft;state.recipes[x.type][x.meal][x.macro]=state.recipes[x.type][x.meal][x.macro].filter(o=>o.id!==x.option.id);save();close();render();}break;
case 'choose-option':todayData().choices[mealKey(d.meal,d.macro)]=d.id;save();render();break;
case 'copy-diet':{const to=state.dietType==='train'?'rest':'train';if(confirm('将当前日型的全部食谱组合复制到另一日型？目标和分配比例不变，另一日型原有食谱将被替换。')){state.recipes[to]=C.copy(state.recipes[state.dietType]);save();toast('食谱组合已复制');}break;}
case 'food-filter':foodFilter=d.k;render();break;
case 'edit-food':editFood(d.id);break;
case 'clone-food':editFood(d.id,true);break;
case 'food-use':foodUse(d.id);break;
case 'delete-food':if(confirm('删除此自定义食物？已引用的食谱会显示缺失，需重新选择食物。')){state.foods=state.foods.filter(f=>f.id!==d.id);save();close();render();}break;
case 'schedule-day':scheduleDay=d.day;render();break;
case 'check-schedule':{const v=todayData(),i=v.checks.indexOf(d.id);if(i<0)v.checks.push(d.id);else v.checks.splice(i,1);save();render();break;}
case 'edit-event':editEvent(d.id);break;
case 'delete-event':if(confirm('删除这条作息？')){state.schedule.days[scheduleDay]=state.schedule.days[scheduleDay].filter(r=>r.id!==d.id);save();close();render();}break;
case 'copy-schedule':form('复制当前作息','copy-schedule',`<div class="notice field full">将用${C.DAY_NAMES[C.DAYS.indexOf(scheduleDay)]}的作息替换勾选日期。原有内容会被覆盖。</div><div class="field full stack">${C.DAYS.filter(d=>d!==scheduleDay).map(d=>`<label class="inline-check"><input type="checkbox" name="targets" value="${d}">${C.DAY_NAMES[C.DAYS.indexOf(d)]}</label>`).join('')}</div>`);break;
case 'schedule-example':if(confirm('用一组可编辑的示例替换当前这一天？请自行调整，示例并非作息建议。')){state.schedule.days[scheduleDay]=[['07:30','08:00','起床与洗漱'],['08:00','08:30','早餐'],['12:30','13:00','午餐'],['18:00','18:30','练前餐'],['19:00','20:30','训练（按计划调整）'],['20:30','21:00','晚餐'],['23:30','07:30','睡觉']].map(([start,end,title])=>({id:C.uid(),start,end,title,notes:''}));save();render();}break;
case 'schedule-notes':form('一周备注','schedule-notes',area('备注','notes',state.schedule.notes,'maxlength="3000"'));break;
case 'backup':exportBackup();break;
case 'raw-backup':download(new Blob([corruptRaw],{type:'application/json'}),'燃刻_待恢复原始数据.json');break;
case 'import':$('importFile').click();break;
case 'confirm-import':if(!pendingImport)break;if(!confirm('确认已备份，替换本机数据？'))break;state=pendingImport;pendingImport=null;corruptRaw=null;conflictBlocked=false;save();close();render();toast(storageBlocked?'已读取备份，但未能保存到本机':'导入完成，请核对目标和食谱');break;
case 'reset':if(confirm('清空此应用在本机的所有计划和训练记录？请先导出备份。')&&confirm('再次确认：清空后只能从你自己的备份恢复。')){state=C.defaults();corruptRaw=null;conflictBlocked=false;save();render();toast(storageBlocked?'本机未能写入清空结果，请检查存储权限':'本机数据已清空；可从已有备份恢复');}break;
case 'check-update':if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();if(reg){await reg.update();toast(reg.waiting?'有新版本，请使用顶部更新按钮':'已检查更新');}else toast('需通过 HTTPS 网站打开，首次联网后启用');}else toast('当前浏览器不支持离线安装');break;
case 'update-app':if($('editor').open){toast('请先保存或关闭正在编辑的表单，再更新');break;}if(waitingWorker&&save()){waitingWorker.postMessage({type:'SKIP_WAITING'});}else toast('请先保存或导出备份，再更新');break;
case 'export-image':await exportImage(d.kind);break;
case 'download-image':if(exportBlob)download(exportBlob,exportName);break;
case 'share-image':if(exportBlob&&navigator.canShare?.({files:[new File([exportBlob],exportName,{type:'image/png'})]}))await navigator.share({files:[new File([exportBlob],exportName,{type:'image/png'})]});else toast('当前浏览器不支持图片分享，请下载或长按图片');break;
}}catch(e){toast(e.message||'操作未完成，请稍后重试');}});
document.addEventListener('submit',event=>{const f=event.target.closest('[data-form]');if(!f)return;event.preventDefault();const v=Object.fromEntries(new FormData(f)),kind=f.dataset.form;try{switch(kind){
case 'profile':{const p=C.copy(state.profile);for(const k of ['gender','goalStartDate'])p[k]=v[k];for(const k of ['weight','height','age','targetWeight','goalWeeks','level','aerobic','protein'])p[k]=Number(v[k]);state.profile=p;state.profileReady=true;break;}
case 'day':Object.assign(currentDay(),{name:v.name.trim(),parts:v.parts.trim(),notes:v.notes});break;
case 'exercise':{if(!v.name.trim())return toast('请填写动作名称');const es=currentDay().exercises,e=C.normalizeExercise({...v,id:f.dataset.id||C.uid()}),i=es.findIndex(x=>x.id===e.id);if(i>=0)es[i]=e;else es.push(e);break;}
case 'week':for(const d of C.DAYS)currentPlan().week[d]=v[d];break;
case 'splits':{const t=state.dietType,proposed={};for(const m of C.MEALS)proposed[m]={carbs:Number(v[m+'_carbs']),protein:Number(v[m+'_protein'])};state.mealSplits[t]=proposed;break;}
case 'option':{syncOptionDraft();const d=optionDraft;if(!d.option.components.length)return toast('请至少加入一种食物');if(d.option.components.some(c=>!C.food(state,c.foodId)))return toast('请移除缺失食物后保存');const arr=state.recipes[d.type][d.meal][d.macro],i=arr.findIndex(o=>o.id===d.option.id);if(i>=0)arr[i]=C.copy(d.option);else arr.push(C.copy(d.option));break;}
case 'food-use':state.dietType=v.type;save();optionEditor(v.meal,v.macro,null,f.dataset.id);return;
case 'food':{const max=v.measure==='perItem'?5000:100;if(['carbs','protein','fat'].some(k=>Number(v[k])>max))return toast(`此计量方式下每项营养素不能超过 ${max}g`);const food=C.normalizeFood({...v,id:f.dataset.id||C.uid()}),i=state.foods.findIndex(x=>x.id===food.id);if(i>=0)state.foods[i]=food;else state.foods.push(food);break;}
case 'event':{if(!v.title.trim())return toast('请填写事项名称');const rows=state.schedule.days[scheduleDay],r={id:f.dataset.id||C.uid(),start:v.start,end:v.end,title:v.title.trim(),notes:v.notes},i=rows.findIndex(x=>x.id===r.id);if(i>=0)rows[i]=r;else rows.push(r);rows.sort((a,b)=>a.start.localeCompare(b.start));break;}
case 'copy-schedule':{const days=new FormData(f).getAll('targets');if(!days.length)return toast('请至少选择一天');if(!confirm('确认替换所选日期的作息？'))return;for(const d of days)state.schedule.days[d]=state.schedule.days[scheduleDay].map(r=>({...C.copy(r),id:C.uid()}));break;}
case 'schedule-notes':state.schedule.notes=v.notes;break;
}save();close();render();toast(storageBlocked||corruptRaw||conflictBlocked?'修改仅在内存中，请导出备份':'已保存');}catch(e){toast('保存失败：'+e.message);}});
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.log){const e=state.strength.active?.exercises[Number(el.dataset.e)],s=e?.setsLog[Number(el.dataset.s)];if(s){s[el.dataset.log]=el.value;save();}}if(el.dataset.splitMacro)updateSplitTotals();if(el.id==='sessionNotes'&&state.strength.active){state.strength.active.notes=el.value;save();}if(el.id==='foodSearch'){foodQuery=el.value;$('foodResults').innerHTML=foodResults();}if(el.id==='pickerSearch')$('pickerResults').innerHTML=pickerRows(el.value);});
document.addEventListener('change',event=>{if(event.target.matches('[data-nuts]')){todayData().nuts=event.target.checked;save();}if(event.target.id==='importFile')importFile(event.target.files[0]);});
window.addEventListener('hashchange',()=>{close();render();window.scrollTo(0,0);});
window.addEventListener('storage',event=>{if(event.key!==STORE)return;conflictBlocked=true;$('critical').textContent='另一窗口更改了本机数据，已暂停本窗口自动保存。请先导出当前备份，再刷新读取最新数据；避免在多个窗口同时编辑。';$('critical').hidden=false;$('saveState').textContent='多窗口冲突 · 未保存';});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(!corruptRaw)save();}else{renderTimer();if(route==='today')render();}});
// Optional wide image exports use local Canvas. No remote capture library.
let exportBlob=null,exportName='';
function exportSections(kind){if(kind==='schedule')return C.DAYS.map((d,i)=>({title:C.DAY_NAMES[i],lines:state.schedule.days[d].length?state.schedule.days[d].map(r=>`${r.start}–${r.end<r.start?'次日 ':''}${r.end}  ${r.title}${r.notes?' · '+r.notes:''}`):['尚未安排']}));const t=state.dietType;return C.MEALS.map(m=>{const target=C.mealTarget(state,t,m),lines=[target?`目标：碳水 ${target.carbs}g / 蛋白质 ${target.protein}g`:'尚未设置营养目标'];for(const k of ['carbs','protein']){const o=currentChoice(m,k,t);lines.push(k==='carbs'?'碳水 · 今日选用':'蛋白质 · 今日选用');if(!o)lines.push('尚未安排');else{const result=C.optionResult(state,o,k,target?.[k]||0);for(const x of result.items)lines.push(`${x.name}  ${target&&!x.missing?n(x.quantity)+x.unit:'—'}${x.estimated?'（参考估算）':''}`);}}return {title:C.MEAL_NAMES[m],lines};});}
async function exportImage(kind){const sections=exportSections(kind),width=1440,colWidth=648,pad=54,gap=36,ctx=document.createElement('canvas').getContext('2d');ctx.font='30px -apple-system, BlinkMacSystemFont, sans-serif';const wrap=(s,w,font=30)=>{ctx.font=`${font}px -apple-system, BlinkMacSystemFont, sans-serif`;const lines=[];for(const para of String(s).split('\n')){let line='';for(const ch of para){if(ctx.measureText(line+ch).width>w&&line){lines.push(line);line=ch;}else line+=ch;}lines.push(line);}return lines;};const blocks=sections.map(s=>({...s,wrapped:s.lines.flatMap(l=>wrap(l,colWidth-56)),height:0}));blocks.forEach(b=>b.height=95+b.wrapped.length*44);const rows=[];for(let i=0;i<blocks.length;i+=2)rows.push(Math.max(blocks[i].height,blocks[i+1]?.height||0));const note=kind==='diet'?C.NUTS+' 坚果营养未计入；仅导出今日选用方案。参考数据不完整，非实际摄入。':state.schedule.notes||'七天独立安排 · 具体时间按实际调整';const noteLines=wrap(note,width-pad*2-44,27),height=244+rows.reduce((a,b)=>a+b+gap,0)+noteLines.length*40+110;if(height>10000)return toast('内容过多，图片会太大。请减少备注或使用应用查看。');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.fillStyle='#f3f5f2';c.fillRect(0,0,width,height);c.fillStyle='#153e34';c.fillRect(0,0,width,188);c.fillStyle='#d2eca5';c.font='24px sans-serif';c.fillText('燃刻 / 我的健身计划',pad,54);c.fillStyle='white';c.font='bold 50px sans-serif';c.fillText(kind==='schedule'?'一周作息表':(state.dietType==='train'?'训练日':'休息日')+'食谱',pad,122);c.font='24px sans-serif';c.fillText(C.dateKey(),width-210,122);let y=224;for(let i=0;i<blocks.length;i+=2){const h=rows[i/2];for(let j=0;j<2;j++){const b=blocks[i+j];if(!b)continue;const x=pad+j*(colWidth+gap);c.fillStyle='white';c.fillRect(x,y,colWidth,h);c.fillStyle='#153e34';c.font='bold 34px sans-serif';c.fillText(b.title,x+28,y+51);c.font='30px sans-serif';c.fillStyle='#42564a';b.wrapped.forEach((l,k)=>c.fillText(l,x+28,y+100+k*44));}y+=h+gap;}c.fillStyle='#43573c';c.font='27px sans-serif';noteLines.forEach((l,i)=>c.fillText(l,pad,y+32+i*40));const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('图片生成失败');exportBlob=blob;exportName=`燃刻_${kind==='schedule'?'作息表':'食谱'}_${C.dateKey()}.png`;if(exportUrl)URL.revokeObjectURL(exportUrl);exportUrl=URL.createObjectURL(blob);dialog('宽版'+(kind==='schedule'?'作息表':'食谱'),`<p class="muted smalltext">1440px 宽、双栏布局。可下载、分享，或长按图片保存；食谱只包含今日选用的方案。</p><img class="export-image" src="${exportUrl}" alt="${kind==='schedule'?'作息表':'食谱'}预览"><div class="actions">${btn('download-image','下载 PNG',{},'primary')}${btn('share-image','系统分享')}</div>`);}
async function initOffline(){if(!('serviceWorker'in navigator)||location.protocol==='file:')return;try{const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});const ready=await navigator.serviceWorker.ready;const names=await caches.keys();offlineReady=names.some(k=>k.startsWith('ranke-shell-'));if($('offlineStatus'))$('offlineStatus').textContent=offlineReady?'已缓存核心文件':'等待首次缓存';const show=()=>{if(reg.waiting){waitingWorker=reg.waiting;$('updateBanner').hidden=false;}};show();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'){offlineReady=true;if($('offlineStatus'))$('offlineStatus').textContent='已缓存核心文件';show();}});});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(waitingWorker&&!reloading){reloading=true;location.reload();}});}catch(e){if($('offlineStatus'))$('offlineStatus').textContent='离线缓存未就绪，请联网后重试';}}
load();
render();initOffline();setInterval(renderTimer,1000);
})();
